fragment HomeParts on Home {
  __typename
  language
  heroTitle
  heroSubtitle
  heroCtaLabel
  featuredTitle
  featuredSubtitle
  featuredProducts {
    __typename
    id
    name
    price
    image
    colors
    rating
  }
  projectsTitle
  projectsDescription
  projectsCtaLabel
  projectsItems {
    __typename
    id
    title
    image
    alt
  }
  ctaTitle
  ctaParagraphs
  ctaBullets
  ctaButtonLabel
  ctaImageAlt
  trustTitle
  trustSubtitle
  trustCtaLabel
}

fragment AboutParts on About {
  __typename
  language
  heroTitleTop
  heroTitleBottom
  heroImage
  heroImageAlt
  quote
  points {
    __typename
    title
    text
    image
    imageAlt
  }
}

fragment SectionsParts on Sections {
  __typename
  language
  title
  excerpt
  body
}
