fragment HomeHeroParts on HomeHero {
  __typename
  title
  subtitle
  ctaLabel
  images {
    __typename
    url
    alt
  }
}

fragment HomeFeaturedProductsParts on HomeFeaturedProducts {
  __typename
  title
  subtitle
  products {
    __typename
    id
    name
    price
    image
    colors
    rating
  }
}

fragment HomeProjectsParts on HomeProjects {
  __typename
  title
  description
  ctaLabel
  items {
    __typename
    id
    title
    image
    alt
  }
}

fragment HomeCtaParts on HomeCta {
  __typename
  title
  paragraphs
  bullets
  buttonLabel
  image
  imageAlt
}

fragment HomeTrustBannerParts on HomeTrustBanner {
  __typename
  title
  subtitle
  ctaLabel
}

fragment AboutHeroParts on AboutHero {
  __typename
  titleTop
  titleBottom
  image
  imageAlt
}

fragment AboutQuoteParts on AboutQuote {
  __typename
  quote
}

fragment AboutStoryPointsParts on AboutStoryPoints {
  __typename
  points {
    __typename
    title
    text
    image
    imageAlt
  }
}

fragment FooterParts on Footer {
  __typename
  contact {
    __typename
    title
  }
}
