//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  home: Home;
  homeConnection: HomeConnection;
  sections: Sections;
  sectionsConnection: SectionsConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomeConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
};


export type QuerySectionsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySectionsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SectionsFilter>;
};

export type DocumentFilter = {
  home?: InputMaybe<HomeFilter>;
  sections?: InputMaybe<SectionsFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Home | Sections | Folder;

export type HomeFeaturedProducts = {
  __typename?: 'HomeFeaturedProducts';
  id: Scalars['String']['output'];
  name: Scalars['String']['output'];
  price: Scalars['Float']['output'];
  image: Scalars['String']['output'];
  colors?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  rating?: Maybe<Scalars['Float']['output']>;
};

export type HomeProjectsItems = {
  __typename?: 'HomeProjectsItems';
  id: Scalars['Float']['output'];
  title: Scalars['String']['output'];
  image: Scalars['String']['output'];
  alt: Scalars['String']['output'];
};

export type Home = Node & Document & {
  __typename?: 'Home';
  language: Scalars['String']['output'];
  heroTitle: Scalars['String']['output'];
  heroSubtitle: Scalars['String']['output'];
  heroCtaLabel: Scalars['String']['output'];
  featuredTitle: Scalars['String']['output'];
  featuredSubtitle: Scalars['String']['output'];
  featuredProducts?: Maybe<Array<Maybe<HomeFeaturedProducts>>>;
  projectsTitle: Scalars['String']['output'];
  projectsDescription: Scalars['String']['output'];
  projectsCtaLabel: Scalars['String']['output'];
  projectsItems?: Maybe<Array<Maybe<HomeProjectsItems>>>;
  ctaTitle: Scalars['String']['output'];
  ctaParagraphs: Array<Scalars['String']['output']>;
  ctaBullets: Array<Scalars['String']['output']>;
  ctaButtonLabel: Scalars['String']['output'];
  ctaImageAlt: Scalars['String']['output'];
  trustTitle: Scalars['String']['output'];
  trustSubtitle: Scalars['String']['output'];
  trustCtaLabel: Scalars['String']['output'];
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type HomeFeaturedProductsFilter = {
  id?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  price?: InputMaybe<NumberFilter>;
  image?: InputMaybe<StringFilter>;
  colors?: InputMaybe<StringFilter>;
  rating?: InputMaybe<NumberFilter>;
};

export type HomeProjectsItemsFilter = {
  id?: InputMaybe<NumberFilter>;
  title?: InputMaybe<StringFilter>;
  image?: InputMaybe<StringFilter>;
  alt?: InputMaybe<StringFilter>;
};

export type HomeFilter = {
  language?: InputMaybe<StringFilter>;
  heroTitle?: InputMaybe<StringFilter>;
  heroSubtitle?: InputMaybe<StringFilter>;
  heroCtaLabel?: InputMaybe<StringFilter>;
  featuredTitle?: InputMaybe<StringFilter>;
  featuredSubtitle?: InputMaybe<StringFilter>;
  featuredProducts?: InputMaybe<HomeFeaturedProductsFilter>;
  projectsTitle?: InputMaybe<StringFilter>;
  projectsDescription?: InputMaybe<StringFilter>;
  projectsCtaLabel?: InputMaybe<StringFilter>;
  projectsItems?: InputMaybe<HomeProjectsItemsFilter>;
  ctaTitle?: InputMaybe<StringFilter>;
  ctaParagraphs?: InputMaybe<StringFilter>;
  ctaBullets?: InputMaybe<StringFilter>;
  ctaButtonLabel?: InputMaybe<StringFilter>;
  ctaImageAlt?: InputMaybe<StringFilter>;
  trustTitle?: InputMaybe<StringFilter>;
  trustSubtitle?: InputMaybe<StringFilter>;
  trustCtaLabel?: InputMaybe<StringFilter>;
};

export type HomeConnectionEdges = {
  __typename?: 'HomeConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Home>;
};

export type HomeConnection = Connection & {
  __typename?: 'HomeConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomeConnectionEdges>>>;
};

export type Sections = Node & Document & {
  __typename?: 'Sections';
  language: Scalars['String']['output'];
  title: Scalars['String']['output'];
  excerpt?: Maybe<Scalars['String']['output']>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type SectionsFilter = {
  language?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  excerpt?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type SectionsConnectionEdges = {
  __typename?: 'SectionsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Sections>;
};

export type SectionsConnection = Connection & {
  __typename?: 'SectionsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SectionsConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHome: Home;
  createHome: Home;
  updateSections: Sections;
  createSections: Sections;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationCreateHomeArgs = {
  relativePath: Scalars['String']['input'];
  params: HomeMutation;
};


export type MutationUpdateSectionsArgs = {
  relativePath: Scalars['String']['input'];
  params: SectionsMutation;
};


export type MutationCreateSectionsArgs = {
  relativePath: Scalars['String']['input'];
  params: SectionsMutation;
};

export type DocumentUpdateMutation = {
  home?: InputMaybe<HomeMutation>;
  sections?: InputMaybe<SectionsMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  home?: InputMaybe<HomeMutation>;
  sections?: InputMaybe<SectionsMutation>;
};

export type HomeFeaturedProductsMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['Float']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  colors?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  rating?: InputMaybe<Scalars['Float']['input']>;
};

export type HomeProjectsItemsMutation = {
  id?: InputMaybe<Scalars['Float']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  alt?: InputMaybe<Scalars['String']['input']>;
};

export type HomeMutation = {
  language?: InputMaybe<Scalars['String']['input']>;
  heroTitle?: InputMaybe<Scalars['String']['input']>;
  heroSubtitle?: InputMaybe<Scalars['String']['input']>;
  heroCtaLabel?: InputMaybe<Scalars['String']['input']>;
  featuredTitle?: InputMaybe<Scalars['String']['input']>;
  featuredSubtitle?: InputMaybe<Scalars['String']['input']>;
  featuredProducts?: InputMaybe<Array<InputMaybe<HomeFeaturedProductsMutation>>>;
  projectsTitle?: InputMaybe<Scalars['String']['input']>;
  projectsDescription?: InputMaybe<Scalars['String']['input']>;
  projectsCtaLabel?: InputMaybe<Scalars['String']['input']>;
  projectsItems?: InputMaybe<Array<InputMaybe<HomeProjectsItemsMutation>>>;
  ctaTitle?: InputMaybe<Scalars['String']['input']>;
  ctaParagraphs?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  ctaBullets?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  ctaButtonLabel?: InputMaybe<Scalars['String']['input']>;
  ctaImageAlt?: InputMaybe<Scalars['String']['input']>;
  trustTitle?: InputMaybe<Scalars['String']['input']>;
  trustSubtitle?: InputMaybe<Scalars['String']['input']>;
  trustCtaLabel?: InputMaybe<Scalars['String']['input']>;
};

export type SectionsMutation = {
  language?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  excerpt?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type HomePartsFragment = { __typename: 'Home', language: string, heroTitle: string, heroSubtitle: string, heroCtaLabel: string, featuredTitle: string, featuredSubtitle: string, projectsTitle: string, projectsDescription: string, projectsCtaLabel: string, ctaTitle: string, ctaParagraphs: Array<string>, ctaBullets: Array<string>, ctaButtonLabel: string, ctaImageAlt: string, trustTitle: string, trustSubtitle: string, trustCtaLabel: string, featuredProducts?: Array<{ __typename: 'HomeFeaturedProducts', id: string, name: string, price: number, image: string, colors?: Array<string | null> | null, rating?: number | null } | null> | null, projectsItems?: Array<{ __typename: 'HomeProjectsItems', id: number, title: string, image: string, alt: string } | null> | null };

export type SectionsPartsFragment = { __typename: 'Sections', language: string, title: string, excerpt?: string | null, body?: any | null };

export type HomeQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomeQuery = { __typename?: 'Query', home: { __typename: 'Home', id: string, language: string, heroTitle: string, heroSubtitle: string, heroCtaLabel: string, featuredTitle: string, featuredSubtitle: string, projectsTitle: string, projectsDescription: string, projectsCtaLabel: string, ctaTitle: string, ctaParagraphs: Array<string>, ctaBullets: Array<string>, ctaButtonLabel: string, ctaImageAlt: string, trustTitle: string, trustSubtitle: string, trustCtaLabel: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, featuredProducts?: Array<{ __typename: 'HomeFeaturedProducts', id: string, name: string, price: number, image: string, colors?: Array<string | null> | null, rating?: number | null } | null> | null, projectsItems?: Array<{ __typename: 'HomeProjectsItems', id: number, title: string, image: string, alt: string } | null> | null } };

export type HomeConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomeFilter>;
}>;


export type HomeConnectionQuery = { __typename?: 'Query', homeConnection: { __typename?: 'HomeConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomeConnectionEdges', cursor: string, node?: { __typename: 'Home', id: string, language: string, heroTitle: string, heroSubtitle: string, heroCtaLabel: string, featuredTitle: string, featuredSubtitle: string, projectsTitle: string, projectsDescription: string, projectsCtaLabel: string, ctaTitle: string, ctaParagraphs: Array<string>, ctaBullets: Array<string>, ctaButtonLabel: string, ctaImageAlt: string, trustTitle: string, trustSubtitle: string, trustCtaLabel: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, featuredProducts?: Array<{ __typename: 'HomeFeaturedProducts', id: string, name: string, price: number, image: string, colors?: Array<string | null> | null, rating?: number | null } | null> | null, projectsItems?: Array<{ __typename: 'HomeProjectsItems', id: number, title: string, image: string, alt: string } | null> | null } | null } | null> | null } };

export type SectionsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SectionsQuery = { __typename?: 'Query', sections: { __typename: 'Sections', id: string, language: string, title: string, excerpt?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SectionsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SectionsFilter>;
}>;


export type SectionsConnectionQuery = { __typename?: 'Query', sectionsConnection: { __typename?: 'SectionsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SectionsConnectionEdges', cursor: string, node?: { __typename: 'Sections', id: string, language: string, title: string, excerpt?: string | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const HomePartsFragmentDoc = gql`
    fragment HomeParts on Home {
  __typename
  language
  heroTitle
  heroSubtitle
  heroCtaLabel
  featuredTitle
  featuredSubtitle
  featuredProducts {
    __typename
    id
    name
    price
    image
    colors
    rating
  }
  projectsTitle
  projectsDescription
  projectsCtaLabel
  projectsItems {
    __typename
    id
    title
    image
    alt
  }
  ctaTitle
  ctaParagraphs
  ctaBullets
  ctaButtonLabel
  ctaImageAlt
  trustTitle
  trustSubtitle
  trustCtaLabel
}
    `;
export const SectionsPartsFragmentDoc = gql`
    fragment SectionsParts on Sections {
  __typename
  language
  title
  excerpt
  body
}
    `;
export const HomeDocument = gql`
    query home($relativePath: String!) {
  home(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomeParts
  }
}
    ${HomePartsFragmentDoc}`;
export const HomeConnectionDocument = gql`
    query homeConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomeFilter) {
  homeConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomeParts
      }
    }
  }
}
    ${HomePartsFragmentDoc}`;
export const SectionsDocument = gql`
    query sections($relativePath: String!) {
  sections(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SectionsParts
  }
}
    ${SectionsPartsFragmentDoc}`;
export const SectionsConnectionDocument = gql`
    query sectionsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SectionsFilter) {
  sectionsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SectionsParts
      }
    }
  }
}
    ${SectionsPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      home(variables: HomeQueryVariables, options?: C): Promise<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}> {
        return requester<{data: HomeQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeQueryVariables, query: string}, HomeQueryVariables>(HomeDocument, variables, options);
      },
    homeConnection(variables?: HomeConnectionQueryVariables, options?: C): Promise<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}> {
        return requester<{data: HomeConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomeConnectionQueryVariables, query: string}, HomeConnectionQueryVariables>(HomeConnectionDocument, variables, options);
      },
    sections(variables: SectionsQueryVariables, options?: C): Promise<{data: SectionsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SectionsQueryVariables, query: string}> {
        return requester<{data: SectionsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SectionsQueryVariables, query: string}, SectionsQueryVariables>(SectionsDocument, variables, options);
      },
    sectionsConnection(variables?: SectionsConnectionQueryVariables, options?: C): Promise<{data: SectionsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SectionsConnectionQueryVariables, query: string}> {
        return requester<{data: SectionsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SectionsConnectionQueryVariables, query: string}, SectionsConnectionQueryVariables>(SectionsConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  